version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - henry61024
  versioning-strategy: increase
  ignore:
  - dependency-name: antd
    versions:
    - 4.11.1
    - 4.11.2
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.15.0
    - 4.15.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.17
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.17
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.17
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  commit-message:
    prefix: chore
    include: scope
